export const tables = [
    { id: 1, seats: 2 },
    { id: 2, seats: 2 },
    { id: 3, seats: 2 },
    { id: 4, seats: 2 },
    { id: 5, seats: 4 },
    { id: 6, seats: 4 },
    { id: 7, seats: 4 },
    { id: 8, seats: 4 },
    { id: 9, seats: 4 },
    { id: 10, seats: 6 },
    { id: 11, seats: 6 },
    { id: 12, seats: 6 },
    { id: 13, seats: 6 },
    { id: 14, seats: 10 },
    { id: 15, seats: 15 },
    { id: 16, seats: 20 },
  ];