# Generated by Django 5.1.2 on 2024-11-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="table_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
