# Generated by Django 5.1.2 on 2024-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_table_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="dishes/"),
        ),
    ]
