# Generated by Django 5.1.2 on 2024-12-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_dish_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="table_id",
        ),
        migrations.AddField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu.table",
            ),
        ),
    ]
